I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 14, in script call
    call begin_minigame
  File "game/concoctioncafe.rpy", line 15, in script
    $completed = true
  File "game/concoctioncafe.rpy", line 15, in <module>
    $completed = true
NameError: name 'true' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 14, in script call
    call begin_minigame
  File "game/concoctioncafe.rpy", line 15, in script
    $completed = true
  File "C:\Users\afons\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\afons\Desktop\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/concoctioncafe.rpy", line 15, in <module>
    $completed = true
NameError: name 'true' is not defined

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.3.22090809
CozyJam 1.0
Tue Sep 20 11:52:06 2022
